spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

jwt:
  public-key-path: src/main/resources/public.pem
