spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: Onila@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.pasan: DEBUG
    org.springframework.web: DEBUG